project:
  type: website

website:
  title: "Macro II - Fluctuations - Part II"
  search: false
  sidebar:
      style: "docked"
      contents:
        - section: lectures
          contents:
            - slides/session_1/index.qmd
            - slides/session_2/index.qmd
            - slides/session_3/index.qmd
            - slides/session_4/index.qmd
        - section: tutorials
          contents:
            - tutorials/session_1/index.ipynb
            - tutorials/session_2/index.ipynb
            - tutorials/session_3/index.ipynb
            - tutorials/session_4/index.ipynb
        - section: tutorials (corrections)
          contents:
            - tutorials/session_1/index_correction.ipynb
            - tutorials/session_2/index_correction.ipynb
            - tutorials/session_3/index_correction.ipynb
            - tutorials/session_4/index_correction.ipynb


resources:
  - tutorials/session_2/*.md

format:
  html:
    theme: default
    css: styles.css
    toc: true
  ipynb: default