project:
  type: website

website:
  title: "Macro II - Fluctuations"
  search: false
  sidebar:
      style: "docked"
      contents:
        - section: lectures
          contents:
            - slides/session_1/index.qmd
            - slides/session_2/index.qmd
        - section: tutorials
          contents:
            - tutorials/session_1/index.ipynb
            - tutorials/session_2/index.ipynb

format:
  html:
    theme: default
    css: styles.css
    toc: true
  ipynb: default