with open('slides/session_4/index.qmd', 'r') as f:
    text = f.read()

replacements = [
    ('Intermediation financiere', 'Intermédiation financière'),
    ("L'importance des intermediaires financiers", "L'importance des intermédiaires financiers"),
    ('Marches du credit', 'Marchés du crédit'),
    ('Problemes lies au credit', 'Problèmes liés au crédit'),
    ('La Grande Recession', 'La Grande Récession'),
    ('## Resume', '## Résumé'),
    ('## Menages', '## Ménages'),
    ("conditions d'optimalite", "conditions d'optimalité"),
    ('optimalite)', 'optimalité)'),
    ('Equilibre des marches', 'Équilibre des marchés'),
    ("Proprietes de l'etat stationnaire", "Propriétés de l'état stationnaire"),
    ('## Premiere simulation', '## Première simulation'),
    ('Modele etendu', 'Modèle étendu'),
    ("Resultats d'estimation", "Résultats d'estimation"),
    ('Pouvoir predictif du modele', 'Pouvoir prédictif du modèle'),
    ('intermediaires financiers', 'intermédiaires financiers'),
    ('intermediaires etaient', 'intermédiaires étaient'),
    ('intermediaires', 'intermédiaires'),
    ('intermedient les fonds', 'intermédient les fonds'),
    ('intermediation', 'intermédiation'),
    ('laureat', 'lauréat'),
    ('president de', 'président de'),
    ('succedant', 'succédant'),
    ('surnomme', 'surnommé'),
    ('specialiste', 'spécialiste'),
    ('necessite', 'nécessité'),
    ('integrees', 'intégrées'),
    ('asymetrique', 'asymétrique'),
    ('selection adverse', 'sélection adverse'),
    ('preteurs', 'prêteurs'),
    ('preteur\b', 'prêteur'),
    ('des prets', 'des prêts'),
    ('aux prets', 'aux prêts'),
    ('les prets', 'les prêts'),
    ('sur prets', 'sur prêts'),
    ('prets evoluent', 'prêts évoluent'),
    ('prets de la', 'prêts de la'),
    ('pret commercial', 'prêt commercial'),
    ("d'un pret", "d'un prêt"),
    ('collatera', 'collatéra'),
    ("D'apres", "D'après"),
    ('emission obligataire', 'émission obligataire'),
    (' cout ', ' coût '),
    ('Le cout', 'Le coût'),
    ('les couts', 'les coûts'),
    ("Couts d'ajustement", "Coûts d'ajustement"),
    ("cout d'ajustement", "coût d'ajustement"),
    ('cout des facteurs', 'coût des facteurs'),
    ("taux d'interet", "taux d'intérêt"),
    ("d'interet sans risque", "d'intérêt sans risque"),
    ('macroeconomiques', 'macroéconomiques'),
    ('macroeconomique', 'macroéconomique'),
    ('differente pour', 'différente pour'),
    ('cle de la', 'clé de la'),
    ('litterature', 'littérature'),
    ('Accelerateur financier', 'Accélérateur financier'),
    ('plus elevee', 'plus élevée'),
    ('sante financiere', 'santé financière'),
    ('degrade la', 'dégrade la'),
    ('amplifies', 'amplifiés'),
    ('deterioration', 'détérioration'),
    ('financieres', 'financières'),
    ('financiere', 'financière'),
    ('methodologie', 'méthodologie'),
    ('resulte de', 'résulte de'),
    ('hypothcaire', 'hypothécaire'),
    ('vulnerables', 'vulnérables'),
    ('predisaient', 'prédisaient'),
    ('reelles', 'réelles'),
    ('specialise en', 'spécialisé en'),
    ('declenchees', 'déclenchées'),
    ('peu publie', 'peu publié'),
    ('agregativement', 'agrégativement'),
    ('epargnant net', 'épargnant net'),
    ('epargnants patients', 'épargnants patients'),
    ('dependant du', 'dépendant du'),
    ("c'est-a-dire", "c'est-à-dire"),
    ('preferences sont', 'préférences sont'),
    ('de facon a', 'de façon à'),
    ("a l'equilibre", "à l'équilibre"),
    ('la quantite', 'la quantité'),
    ('representatif choisit', 'représentatif choisit'),
    ('parametres de preference', 'paramètres de préférence'),
    ('parametres de levier', 'paramètres de levier'),
    ('parametre de preference', 'paramètre de préférence'),
    ('Parametre de preference', 'Paramètre de préférence'),
    ('contrainte budgetaire', 'contrainte budgétaire'),
    ('remuneres', 'rémunérés'),
    ('Hypothese technique', 'Hypothèse technique'),
    ('Hypothese : ', 'Hypothèse : '),
    ('est suppose', 'est supposé'),
    ("l'etat stationnaire", "l'état stationnaire"),
    ('etat stationnaire', 'état stationnaire'),
    ('equivalent a ', 'équivalent à '),
    ('microfonde et', 'microfondé et'),
    ('microfonde,', 'microfondé,'),
    ('Periode de temps', 'Période de temps'),
    ('elasticite de', 'élasticité de'),
    ('residentiel)', 'résidentiel)'),
    ('est paye', 'est payé'),
    ('reponse du', 'réponse du'),
    ('calibre sur', 'calibré sur'),
    ('deviation exogene', 'déviation exogène'),
    ('systeme financier', 'système financier'),
    ('estime par', 'estimé par'),
    ('bayesienne', 'bayésienne'),
    ('attribue aux', 'attribué aux'),
    ('predictif du', 'prédictif du'),
    ('predit aussi', 'prédit aussi'),
    ("n'etaient pas cibles", "n'étaient pas ciblés"),
    ('probablement ete', 'probablement été'),
    ('creation monetaire', 'création monétaire'),
    ('Je considere', 'Je considère'),
    ('a un periode', 'à une période'),
    ('a court terme', 'à court terme'),
    ('depots a une', 'dépôts à une'),
    ('des depots', 'des dépôts'),
    ('les depots', 'les dépôts'),
    ('taux de depot', 'taux de dépôt'),
    ('depots des', 'dépôts des'),
    ('depots en', 'dépôts en'),
    ('depot supplementaire', 'dépôt supplémentaire'),
    ('supplementaire de', 'supplémentaire de'),
    ("d'efficacite", "d'efficacité"),
    ('capacites d', 'capacités d'),
    ('la capacite', 'la capacité'),
    ('doit etre payee', 'doit être payée'),
    ('etre payee', 'être payée'),
    ('etre plus', 'être plus'),
    ('peuvent etre', 'peuvent être'),
    ('etaient des', 'étaient des'),
    ('etaient *', 'étaient *'),
    ('epargnant', 'épargnant'),
    ('recessions', 'récessions'),
    ('modelisation', 'modélisation'),
    ('un role', 'un rôle'),
    ('le modele', 'le modèle'),
    ('Un modele', 'Un modèle'),
    ('un modele', 'un modèle'),
    ('du modele', 'du modèle'),
    ('modele DSGE', 'modèle DSGE'),
    ('modeles realistes', 'modèles réalistes'),
    ('modeles DSGE', 'modèles DSGE'),
    ('modele complet', 'modèle complet'),
    ('integre des', 'intégré des'),
    ('Recession', 'Récession'),
    ('monetaire', 'monétaire'),
    ('activites', 'activités'),
    ('etait un', 'était un'),
    ('etaient', 'étaient'),
    ('auraient du', 'auraient dû'),
    ('creer davantage', 'créer davantage'),
    ('faire face', 'faire face'),
    ('la necessite', 'la nécessité'),
    ('Notons :', 'Notons :'),
]

for old, new in replacements:
    text = text.replace(old, new)

with open('slides/session_4/index.qmd', 'w') as f:
    f.write(text)
print('Done')
